### ISSUE TITLE
hyprcursor-util extraction fails with parentheses in directory name

### ISSUE THREAD

**Issue by RadicalityIncident** [hyprwm/hyprcursor#10]
When running hyprcursor-util --extract on a directory with a paren in the name extraction fails with the following error

```
Found xcursor lr_angle
sh: -c: line 1: syntax error near unexpected token `('
sh: -c: line 1: `rm -f /tmp/hyprcursor-util/* && cd /tmp/hyprcursor-util && xcur2png /home/radical/HyprcursorTest/Capitaine Cursors (Gruvbox)/cursors/lr_angle -d /tmp/hyprcursor-util 2>&1'
Failed: Failed reading xconfig for /home/radical/HyprcursorTest/Capitaine Cursors (Gruvbox)/cursors/lr_angle
```

In my case the folder name was `Capitaine Cursors (Gruvbox)` , I tested that it was in fact just the paren causing the issue by renaming the directory `test` and the extraction completed successfully. Running it again after renaming the directory `test(` caused it to fail again.

**Comment by vaxerski** [comment]
check above

**Comment by RadicalityIncident** [comment]
Fixes it for me!
