### ISSUE TITLE
Hyprland crashes with svg-cursor for left pointer

### ISSUE THREAD

**Issue by loaidheach** [hyprwm/hyprcursor#13]
I tried to convert my customized Bibata-Modern cursor, extraced via `hyprcursor-util`, replaced pngs with svgs from Bibata_Cursor repo (unmodified blue/green "original" files to see changes), compiled it and moved it to `~/.local/share/icons`. No env variable set or anything.
The theme seems to be used automatically. This causes Hyprland to crash immediately on launch (log is attached). If I use the extraced png-version of the left pointer, everthing works fine. I can also just delete left_ptr.hlc from the compiled cursor and it will work as well, though without a default pointer. I also tried replacing the svg with one of the working cursors, it made no difference. I also attached the meta.hl for the cursor file.
Considering the exact cursor that causing me problems is _the_ example from your blog post, I may be doing something wrong here.

System: Fedora 39
Hyprland 0.37.1
hyprcursor 0.1.4
both installed from https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/
This is a laptop with an external screen, internal and external use different scaling (probably not relevant in this case).

[meta.hl.txt](https://github.com/hyprwm/hyprcursor/files/14697066/meta.hl.txt)

[hyprlandCrashReport80840.txt](https://github.com/hyprwm/hyprcursor/files/14697036/hyprlandCrashReport80840.txt)

**Comment by loaidheach** [comment]
Sure thing, I included both the source (extracted_Bibata-Modern-Classic) as well as the compiled theme (theme_Bibata-Modern-Mocha) and a short Readme on how I partially scripted the conversion.

[full_theme.zip](https://github.com/hyprwm/hyprcursor/files/14704351/full_theme.zip)

**Comment by vaxerski** [comment]
this is odd.. I had some god-knows-what version and it was bugged, I compiled latest and it fixed itself.

**Comment by vaxerski** [comment]
Since this is svg, make double triple quadruple sure you are not on 0.1.3, svgs are broken on that ver

**Comment by loaidheach** [comment]
`hyprcursor-util --version` says it's 0.1.4, to be really extra sure I compiled hyprcursor-util from git, that got me the same behavior. It's also strange that all other cursor shapes except the default pointer work.
I guess I'll play around with other cursor themes or other versions of Bibata and see what happens there and report my findings.

**Comment by vaxerski** [comment]
I mean the lib

**Comment by loaidheach** [comment]
I checked that as well, it's `libhyprcursor.so.0.1.4`, even tried in an Arch VM, just to make absolutely sure. Same issue. 

I finally got it working after compiling and successfully trying the GoogleBlackDot from Discord. For some reason the size parameter causes the issue. Changing
`define_size = 24, left_ptr.svg` 
to 
`define_size = 22, left_ptr.svg`
in `left_ptr/meta.hl` fixes the issue. Changing it back again causes the crash. All other cursor shapes in my theme use `24` and work fine. Not very satisfying, but it works.
Likewise changing the `22` to `24` in the `left_ptr/meta.hl` in GoogleBlackDot (and nothing else) causes the theme to crash Hyprland as well.

**Comment by vaxerski** [comment]
hm, does setting it to 0 fix it? maybe I should internally force size 0 on svg

**Comment by loaidheach** [comment]
Setting it to 0 works as well. Forcing it internally during compilation seems like a good idea.

**Comment by vaxerski** [comment]
not during compilation, but during loading xD

**Comment by vaxerski** [comment]
check now

**Comment by loaidheach** [comment]
Works for me 👍
