### ISSUE TITLE
Cursor goes to largest size when using fractional scaling and png cursors

### ISSUE THREAD

**Issue by Yohannnn** [hyprwm/hyprcursor#14]
I tried to extract a cursor png theme however when I set my cursor size to 24 the cursor was massive. I noticed that when I switched from my normal scale of 1.6 to 1 the cursor size went back to normal. It seems like it's just defaulting to the largest cursor size when using fractional scaling.

**Comment by vaxerski** [comment]
can you try compiling and using the test to render a cursor at `24 * 2` (aka 48) and seeing if it turns out "massive"?

**Comment by Yohannnn** [comment]
When I switch to using a scale of 2 instead of 1.6 the cursor is the correct size.

**Comment by vaxerski** [comment]
that does not answer my question

**Comment by Yohannnn** [comment]
Sorry, I misunderstood the question, setting the size to 48 with hyprctl still gives the same size cursor as 24. I've done some more testing and I've found some very weird behavior. Trying to use a size 1-9 results in a cursor slightly smaller than the xcursor which is using the theme that I extracted this hyprcursor theme from at a size of 24. Trying sizes 10-14 is decently bigger than the xcursor. 15 is smaller than the size from setting it to a size in 1-9. 16-19 is the same as 10-14. 20 Is the same as 1-9. 21-29 gives me the largest size ive seen so far. 30 is slightly larger than the xcursor. I'm not sure if there is a pattern here but either way this doesn't feel like it should be the correct behavior.

**Comment by vaxerski** [comment]
what's the resampling setting on the cursor shapes?

**Comment by Ondra3211** [comment]
Hi, I have the same issue. I am using Adwaita theme from /usr/share/icons/Adwaita on Arch. My scale factor is set to 1.25
Idk what you mean by resampling setting but I tried all the algorithms.
--resize none => huge size but sharp
--resize nearest => right size but pixelated
--resize bilinear => right size but blurry

**Comment by vaxerski** [comment]
that's expected for png cursors. Use an svg theme for the right size without any pixelation/blur.

**Comment by Agent00Ming** [comment]
@vaxerski I think this is what https://github.com/hyprwm/Hyprland/issues/6017 is referring to

**Comment by hdm9527** [comment]
reason https://github.com/hyprwm/Hyprland/issues/6017#issuecomment-2106240673

**Comment by vaxerski** [comment]
yea, needs a fix
