### ISSUE TITLE
Cursor Size ignored on most apps/layer

### ISSUE THREAD

**Issue by Pummelfisch** [hyprwm/hyprcursor#17]
# Main Problem
I've extracted a png cursor theme and replaced all the png files with one svg-file for the whole set. It seems that this also worked, sinde the correct cursor-theme is displayed using this part in the `hyprland.conf`

```
# Environment Variables
env = HYPRCURSOR_THEME,"Future Cyan"
env = HYPRCURSOR_SIZE,30
```

However the icons are correct but the size is ignored by most layers or applications. For example the main desktop (without anything open, so only wallpaper visible) shows the smalles possible option (size 24). Brave browser behaves the same.
In some layers, for example VSCodium (Wayland mode) or even on waybar the actual setting is performed and the cursor switches to the size I've defined.

## Additional Information
In all of the `meta.hl`-files I did define the size 24 for the svg. This is supposed too be no problem, if i understood the doc correctly. Here is an example-file:
```
resize_algorithm = bilinear
hotspot_x = 0.17
hotspot_y = 0.17

define_override = default
define_override = left_ptr

define_size = 24, arrow.svg
```

I've also tried to use size 0 in the `define_size` block, based on this comment:

"svg should always have the size 0, as they do not have a size. Multiple svg will be treated as an animation."
_Originally posted by @vaxerski in https://github.com/hyprwm/hyprcursor/issues/16#issuecomment-2018279026_

However that did not change the behaviour of the corresponding cursor.

**Comment by vaxerski** [comment]
r t f m

https://wiki.hyprland.org/Hypr-Ecosystem/hyprcursor/#important-notes

**Comment by Pummelfisch** [comment]
> r t f m
> 
> https://wiki.hyprland.org/Hypr-Ecosystem/hyprcursor/#important-notes

I did, but maybe i dont understand or miss something?
I also export `XCURSOR_THEME` and `XCURSOR_SIZE` to the according theme.
However nothing there would explain why the cursor size is smaller then what i set it to, espacilly on the desktop without any application running in the foreground.

**Comment by vaxerski** [comment]
without apps in the foreground, your wallpaper utility sets the cursor...

**Comment by Pummelfisch** [comment]
> without apps in the foreground, your wallpaper utility sets the cursor...

Thanks for the clarification. I am using hyprpaper and still would assume that here the cursor-size of hyprcursor would be used. Even when I'm not using any wallpaper utility, so staying with the default wallpaper and hypr-chan, I'm still stuck with a smaller cursor then what i set it to.

**Comment by Pummelfisch** [comment]
As mentioned in my original issue, I've already tried that for one cursor file. The corresponding `meta.hl` looked like this:
```
resize_algorithm = bilinear
hotspot_x = 0.17
hotspot_y = 0.17

define_override = default
define_override = left_ptr

define_size = 0, arrow.svg
```

I did not do this for all the cursors in the cursor-theme since it did not result in any change for that one cursor. Or does this only work if all svg curosrs are set to size 0?

**Comment by Pummelfisch** [comment]
> As mentioned in my original issue, I've already tried that for one cursor file. The corresponding `meta.hl` looked like this:
> 
> ```
> resize_algorithm = bilinear
> hotspot_x = 0.17
> hotspot_y = 0.17
> 
> define_override = default
> define_override = left_ptr
> 
> define_size = 0, arrow.svg
> ```
> 
> I did not do this for all the cursors in the cursor-theme since it did not result in any change for that one cursor. Or does this only work if all svg curosrs are set to size 0?

Okay I tryed now to change all the cursor sizes to 0 as suspected here and that did work. So for svg-files all cursor sizes have to be set to 0 for it to work.

Thank you @vaxerski for providing support on this and having the patience with me. Oh and in general a big thank you for providing us with these great tools :)

**Comment by vaxerski** [comment]
yeah this was reported before, and a fix is pending for 0.1.6

**Comment by Pummelfisch** [comment]
I am sorry to necro-bomb this and come back to this problem again. Apparently I was a bit hasty with my last comment. The error still persist with all cursor-svgs set to `define_size = 0`. I am not quite sure if this could be a problem with the acutal cursor theme i use or if there is still any other setting i am doing wrong.

I am running the Arch package of hyprcursor which uses version 0.1.5, as far as i know.

**Comment by vaxerski** [comment]
I'll push .6 soon to see if that fixes it
