### ISSUE TITLE
Cursor theme should search in dirs specified by $XDG_DATA_DIRS if present

### ISSUE THREAD

**Issue by jinliu** [hyprwm/hyprcursor#26]
Currently only `$HOME/.local/share` and `/usr/share` are searched. This wouldn't work for KDE devs, as the KDE dev build installs to `$HOME/kde/usr` by default, and adds `$HOME/kde/usr/share` to the front of `$XDG_DATA_DIRS`.

**Comment by vaxerski** [comment]
`$XDG_DATA_DIRS` is user-specific if I understand correctly... so we'd search themes in `$XDG_DATA_DIRS/icons`?

**Comment by Loara** [comment]
> `$XDG_DATA_DIRS` is user-specific if I understand correctly... so we'd search themes in `$XDG_DATA_DIRS/icons`?

`$XDG_DATA_DIRS` should be [system-specific](https://wiki.archlinux.org/title/XDG_Base_Directory#System_directories), `$XDG_DATA_HOME` is instead user-specific.
