### ISSUE TITLE
Can no longer set cursors after v0.1.3 update.

### ISSUE THREAD

**Issue by entailz** [hyprwm/hyprcursor#3]
Was working before I updated. I tried to set one of my cursors "hyprcat" and it set your BimbataSVG example instead. They are not sharing manifest names or file names.

**Comment by vaxerski** [comment]
should be fixed with https://github.com/hyprwm/hyprcursor/commit/e3056efd46c0eef64fa989c8a47676a84051c575

oopsie from my side - I'll make a hotfix in a sec.

**Comment by vaxerski** [comment]
pushed 0.1.4
