### ISSUE TITLE
compile error "round not a member of std"

### ISSUE THREAD

**Issue by umop3plsdn** [hyprwm/hyprcursor#30]
i've got CLANG 17 installed do i need 18? Arch hasn't updated it yet but I can manually compile it if need be.

[  7%] Building CXX object CMakeFiles/hyprcursor.dir/libhyprcursor/hyprcursor.cpp.o
/home/da5id/tmp/hyprcursor/libhyprcursor/hyprcursor.cpp: In member function ‘SCursorImageData** Hyprcursor::CHyprcursorManager::getShapesC(int&, const char*, const Hyprcursor::SCursorStyleInfo&)’:
/home/da5id/tmp/hyprcursor/libhyprcursor/hyprcursor.cpp:338:34: error: ‘round’ is not a member of ‘std’; did you mean ‘std::chrono::round’?
  338 |         data[i]->hotspotX = std::round(hotX * (float)data[i]->size);
      |                                  ^~~~~
In file included from /usr/include/c++/13.2.1/bits/fs_fwd.h:37,
                 from /usr/include/c++/13.2.1/filesystem:48,
                 from /home/da5id/tmp/hyprcursor/libhyprcursor/hyprcursor.cpp:5:
/usr/include/c++/13.2.1/bits/chrono.h:1084:7: note: ‘std::chrono::round’ declared here
 1084 |       round(const time_point<_Clock, _Dur>& __tp)
      |       ^~~~~
/home/da5id/tmp/hyprcursor/libhyprcursor/hyprcursor.cpp:339:34: error: ‘round’ is not a member of ‘std’; did you mean ‘std::chrono::round’?
  339 |         data[i]->hotspotY = std::round(hotY * (float)data[i]->size);
      |                                  ^~~~~
/usr/include/c++/13.2.1/bits/chrono.h:1084:7: note: ‘std::chrono::round’ declared here
 1084 |       round(const time_point<_Clock, _Dur>& __tp)
      |       ^~~~~
make[2]: *** [CMakeFiles/hyprcursor.dir/build.make:90: CMakeFiles/hyprcursor.dir/libhyprcursor/hyprcursor.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:848: CMakeFiles/hyprcursor.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by vaxerski** [comment]
try

**Comment by h3ss** [comment]
I was having the same error, fixed now

**Comment by umop3plsdn** [comment]
Thanks man
