### ISSUE TITLE
hyprcursor-util ignores overrides

### ISSUE THREAD

**Issue by hweissi** [hyprwm/hyprcursor#36]
Hi,

When trying to build a cursor using hyprctl-util, all my `define_override` settings get ignored.
The log messages show `overrides: 0` for every cursor.

This happens with v0.1.6 and v0.1.7.
The unzipped .hlc files contain a meta.hl where overrides are missing too.

**Comment by vaxerski** [comment]
meta.hl should be copied, so I am unsure how overrides can be _removed_?

Printing 0 is a bug yes

**Comment by vaxerski** [comment]
should be fixed with above

**Comment by hweissi** [comment]
True, seems like I happened to look at a file without overrides.

However, the overrides don't seem to work for me.
When testing with [this website](http://elektronotdienst-nuernberg.de/bugs/cursor.html), I see only the cursors where the directory name matches the requested cursor name.

Do you have any idea how I can debug this issue better?

**Comment by vaxerski** [comment]
seems to be working on my end. Can I get your theme?

**Comment by hweissi** [comment]
[posy.zip](https://github.com/hyprwm/hyprcursor/files/14981211/posy.zip)

**Comment by vaxerski** [comment]
I can see all cursors on the above website working fine. Latest hyprland and hyprcursor.

**Comment by hweissi** [comment]
Interesting. I'm on current hyprland, using the nix flake from git.
Most cursors work, but some things (like ne-resize, s-resize, w-resize) don't. I'll try the tests.

**Comment by hweissi** [comment]
It works for me in the tests. e.g. se-resize renders properly.
Seems to be an issue with chrome?

**Comment by fufexan** [comment]
Just updated most hypr* apps' lockfiles, see if the issue still occurs.

**Comment by hweissi** [comment]
Works now, thanks!
