### ISSUE TITLE
Fix build under Debian sid

### ISSUE THREAD

**Issue by regit** [hyprwm/hyprcursor#37]
Libzip 1.10.1 that is mandatory since 1f4c960cf1c0c9aaf99670c62b6eff751bd67ff0 is not available on distribution like Debian sid so the build is not possible on these distros.

**Comment by vuongtuha** [comment]
Use libzip-dev
apt-cache policy libzip-dev                                              11:28:15
libzip-dev:
  Installed: 1.7.3-1.1+b1
  Candidate: 1.7.3-1.1+b1
  Version table:
 *** 1.7.3-1.1+b1 500
        500 http://deb.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
