### ISSUE TITLE
Cant install with AUR on arch linux

### ISSUE THREAD

**Issue by mooncoffee1** [hyprwm/hyprcursor#4]
hi, the problem is that i cant install hyprcursor from the aur, it needs a bigger hyprlang version.
![image](https://github.com/hyprwm/hyprcursor/assets/118976333/6e9d9326-8a67-47a0-8ad9-bf6debf93007)
but, if i install the git version, then hyprlock and hypridle, sais that they cant find hyprland 0.4.2, or some shit. maybe the hypridle and hyprlock need to be ubdated to hyprlang > 0.4.4 or smth, plase help

**Comment by vaxerski** [comment]
install git of all, arch packaging is very much behind

**Comment by lespea** [comment]
Not a very good start when you're trying to gain adoption

**Comment by vaxerski** [comment]
ah yes sorry mr "I know everything about software" that a package that has barely come out requires new dependencies that arch has not packaged yet (fwiw, others have, like alpine, fedora or nix) 

ref: https://repology.org/project/hyprlang/versions
