### ISSUE TITLE
bug: tag 0.1.8

### ISSUE THREAD

**Issue by mjkx5** [hyprwm/hyprcursor#41]
Arch Linux, hyprland, kitty.

I update hyprcursor from hyprcursor-0.1.7-1-x86_64.pkg.tar.zst  to hyprcursor-0.1.8-1-x86_64.pkg.tar.zst. bug appear.

1. open two application on windows, one of that is kitty.
2. cursor move out of kitty
3. kitty do not work, It is freeze.

then, I paru -U /var/cache/pacman/pkg/hyprcursor-0.1.7-1-x86_64.pkg.tar.zst, back to 0.1.7-1, bug disappears.

**Comment by vaxerski** [comment]
you mean kitty itself is frozen? or just the cursor? I fail to see how that is possible

**Comment by mjkx5** [comment]
@vaxerski  one is kitty, one is chrome. 
when cursor move out of kitty, into chrome. then into kitty, kitty is froze.

**Comment by mjkx5** [comment]
other terminal emulator apears, eg: terminator, alacritty.

**Comment by vaxerski** [comment]
I fail to see how that is possible, and can't repro myself

**Comment by mjkx5** [comment]
It appears my wrong, I uninstall that,  It appears. ohmygod. my wrong.
