### ISSUE TITLE
Cropped cursors from hyprcursor-util

### ISSUE THREAD

**Issue by v4u6h4n** [hyprwm/hyprcursor#44]
Hey there, I've been playing around with `hyrpcursor-util`, converting breeze cursors, and eventually some other major cursor themes, but I've found some of the cursors have cropping. Or there's some other rendering issue that unrelated to the creation.

**Comment by vaxerski** [comment]
I'd suspect an issue with xcur2png then. Are the png files in the working theme cropped too?

**Comment by v4u6h4n** [comment]
The cursors are good in the original theme, and in the png files created during the hyprcursor-util extraction, they are only cropped in the final working state. The default cursor, and a lot of other cursors are fine in the working state; it's only cursors that exceed a certain height and/or width that are cropped.

**Comment by Gigas002** [comment]
Hey, @v4u6h4n!
Can you check out the `meta.hl` files nearby cursors and compare the px sizes? I suspect you might've hit the same issue I did here: https://github.com/hyprwm/Hyprland/issues/6517. 
I've converted my xcursor theme with `hyprcursor-util` too, and didn't notice that difference in `meta.hl` files with actual cursor image sizes.

**Comment by v4u6h4n** [comment]
Hey @Gigas002 yeah sure, I'll have a look, but I can't see a `meta.hl` file; all I have is a `manifest.hl` file in the parent directory and a bunch of `.hlc` files in the `hyprcursors` subdirectory.

**Comment by Gigas002** [comment]
These `.hlc` files are an archives, you can open them and see the cursor `png` images and `meta` file

**Comment by vaxerski** [comment]
to be precise, .hlc is just a .zip

**Comment by vaxerski** [comment]
likely that hyprcursor-util is extracting them incorrectly from XCursor. X's spec allows for this mismatch and does... some weird stuff there. Anyways, this doesn't seem like a case I want to support. Manual intervention is part of life, util's X -> hc conversion is very approximate anyways. Closing :)
