### ISSUE TITLE
Applying theme with svg cursors freezes system for several seconds

### ISSUE THREAD

**Issue by Gigas002** [hyprwm/hyprcursor#48]
So, after my previous problem with `.png` cursors here https://github.com/hyprwm/Hyprland/issues/6517, I've ported theme cursors into `.svg` files. Now cursor works and looks fine, but it takes several seconds to apply cursors for unknown reason now.
Here's archive with icons and a recording of how this is looking on my end.

[Sweet-cursors-hyprcursor.zip](https://github.com/user-attachments/files/15871342/Sweet-cursors-hyprcursor.zip)

https://github.com/hyprwm/hyprcursor/assets/24297712/fe81c9be-5e1e-496f-b542-3312225ff48c

**Comment by vaxerski** [comment]
does it happen with all themes?

**Comment by Gigas002** [comment]
No, this behavior is observed only with this theme

**Comment by vaxerski** [comment]
likely because your SVGs are quite sizeable (especially the animated ones) and take a while to render. Not a bug or anything.
