### ISSUE TITLE
flake: add package for hyprcursor-utils

### ISSUE THREAD

**Issue by ninelore** [hyprwm/hyprcursor#57]
title

for convenience i'd say

thanks

**Comment by vaxerski** [comment]
@fufexan ?

**Comment by fufexan** [comment]
The `hyprcursor` package contains the utils though. And only the utils will be pulled in by default, due to the separation of `-dev` and `-lib` outputs.

**Comment by ninelore** [comment]
Yea i just found it, but not in PATH tho. Would it make sense there?

**Comment by fufexan** [comment]
Should be in PATH if you add the package to either `home.packages` or `environment.systemPackages`. Hyprland only needs the lib, so it won't add the util to PATH.

**Comment by ninelore** [comment]
oh mb then. thanks tho
