### ISSUE TITLE
Cursor disappears on youtube

### ISSUE THREAD

**Issue by Rankarusu** [hyprwm/hyprcursor#6]
So I recently updated hyprland and installed hyprcursor with it. I created a theme with hyprcursor-utils from an xcursor theme (Qogir-dark) and added the following lines to my conf: 
```
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Qogir-dark
env = HYPRCURSOR_THEME,extracted_Qogir-dark
env = HYPRCURSOR_SIZE,24
```

Works well so far. The only problem I face is that my cursor disappears on youtube. Specifically when hovering over the video while the progress bar hides due to cursor inactivity. The cursor disappears with the ui but does not reappear when moved. It only comes back when moving to another screen. This Problem also seems to occur when hovering over embedded videos on other websites.

Tested on both chromium and brave with ozone-platform wayland enabled

**Comment by vaxerski** [comment]
that's not a hyprcursor issue, more like either ff or hyprland

**Comment by Rankarusu** [comment]
In case someone else comes around having the same issue: It was the theme.
Switched to Captaine and everything works again.
