### ISSUE TITLE
Cursor theme not applied with cursor environment variables set in hyprland.conf

### ISSUE THREAD

**Issue by SherLock707** [hyprwm/hyprcursor#62]
I have set the following environment variables in my hyprland.conf to configure the cursor theme and size:

`env = HYPRCURSOR_THEME,Bibata-Modern-Ice`
`env = HYPRCURSOR_SIZE,24`

However, upon boot, it defaults to the regular cursor theme instead of applying the specified theme and size. I have to manually run the following command after boot for the changes to take effect:

Running `hyprctl setcursor "Bibata-Modern-Ice" 24` sets the theme instantly.

`hyprcursor 0.1.9-1`
`hyprland 0.43.0-1`

**Comment by SherLock707** [comment]
My cursor config:
```
cursor {
  no_hardware_cursors = false
  enable_hyprcursor = true
  warp_on_change_workspace = true
  sync_gsettings_theme = true
}
```

**Comment by AQDuck97** [comment]
I'm running into this too.

`hyprland 0.45.2-3`
`hyprcursor 0.1.10-1`
Arch Linux

**Comment by vaxerski** [comment]
this is not a hyprcursor issue, rather a hyprland one, or more likely, user error
