### ISSUE TITLE
Can't use semicolons on define_override

### ISSUE THREAD

**Issue by SeeStarz** [hyprwm/hyprcursor#67]
tbh i don't really know what's going on. i just wanted to port a windows cursor to linux. anyways.
```
define_override = arrow
define_override = default
define_override = top_left_corner
```
seems to work
```
define_override = arrow;default;top_left_corner
```
doesn't
https://standards.hyprland.org/hyprcursor/

**Comment by vaxerski** [comment]
that's correct. `;`s are only for toml. Standard implies hl is fine with that too, I'll fix it.
