### ISSUE TITLE
HYPRCURSOR_SIZE environment variable seems to affect XCURSOR_SIZE, as well

### ISSUE THREAD

**Issue by izmyname** [hyprwm/hyprcursor#72]
For example, if I set `HYPRCURSOR_SIZE=32`, xcursor also gets size 32, although the value of `XCURSOR_SIZE` is `24`. This doesn't happen, however, if I set hyprcursor in `hyprland.conf` with `exec-once = hyprctl setcursor`

**Comment by vaxerski** [comment]
that's not a hyprcursor issue, rather hyprland.
