### ISSUE TITLE
Can't compile with Clang 18

### ISSUE THREAD

**Issue by AngryPenguinPL** [hyprwm/hyprcursor#8]
When trying to compile hypercursor 0.1.4 with Clang 18.1.1 but compilation failed with this error:

```
/builddir/build/BUILD/hyprcursor-0.1.4/libhyprcursor/hyprcursor.cpp:511:36: error: arithmetic on a pointer to void
DEBUG util.py:446:    511 |     std::memcpy(output, DATA->data + DATA->readNeedle, toRead);
DEBUG util.py:446:        |                         ~~~~~~~~~~ ^
DEBUG util.py:446:  1 warning and 1 error generated.
DEBUG util.py:446:  make[2]: *** [CMakeFiles/hyprcursor.dir/build.make:79: CMakeFiles/hyprcursor.dir/libhyprcursor/hyprcursor.cpp.o] Error 1
DEBUG util.py:446:  make[1]: *** [CMakeFiles/Makefile2:864: CMakeFiles/hyprcursor.dir/all] Error 2
DEBUG util.py:446:  make[1]: *** Waiting for unfinished jobs....
```
Full build log:  https://file-store.openmandriva.org/api/v1/file_stores/a426314c66e81d4392317f89a6cb119306d83835.log?show=true

I will add that it compiles correctly when using the GCC compiler, but my distribution tries to compile all (almost) packages with LLVM/Clang.

**Comment by vaxerski** [comment]
under gcc that's just a warning, I guess clang hates it more

**Comment by vaxerski** [comment]
should be done.
